version: '2'

tasks:
  build_docker_minikube:
    desc: Build a docker image in Minikube
    cmds:
      - >
        eval $(minikube docker-env);
        docker build -t fake-bank-backend:latest .;
        eval $(minikube docker-env -u)

  build_docker:
    desc: Build a docker image
    cmds:
      - >
        docker build -t fake-bank-backend:latest .
