server:
  port: 8080
spring:
  application:
    name: fake-bank-backend
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  datasource:
    url: jdbc:postgresql://fake-bank-backend-database:5432/fake-bank-backend
    username: fake-bank-backend
    password: backendPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
    liquibase:
      enabled: false

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: fake-bank-realm
  resource: fake-bank-backend
  public-client: true
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  ssl-required: external

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:fake-bank-backend-test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=false;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/fake-bank-backend
    username: fake-bank-backend
    password: backendPassword
