# Default values for fake-bank-backend.

replicaCount: 1

image:
  repository: fake-bank-backend
  tag: latest
  # As this is only used with Minikube, there is no registry to pull from
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # certmanager.k8s.io/cluster-issuer: letsencrypt
  hosts:
    - host: api.olof.info
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

database:
  fullnameOverride: fake-bank-backend-database
  persistence:
    enabled: false
  global:
    postgresql:
      postgresqlUsername: fake-bank-backend
      postgresqlPassword: backendPassword
      postgresqlDatabase: fake-bank-backend

application:
  profile: default
  server:
    port: 8080

resources:
   limits:
     cpu: 500m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
