name: Fake Bank Backend Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Lint Helm config
      uses: docker://dtzar/helm-kubectl
      with:
        args: helm lint deployment/fake-bank-backend

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk

    - name: Build with Maven
      run: mvn -B package --file pom.xml
